const type = {
    ADD_USER: 'ADD_USER',
    DELETE_USER: 'DELETE_USER',
    SET_CURRENT: 'SET_CURRENT',
    CLEAR_CURRENT: 'CLEAR_CURRENT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    FILTER_CONTACT: 'FILTER_CONTACT',
    CLEAR_FILTER: 'CLEAR_FILTER',
    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT'
}

export default type
